// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// uuid
std::string uuid();
RcppExport SEXP uuidr_uuid() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(uuid());
    return __result;
END_RCPP
}
// uuid_random
std::string uuid_random();
RcppExport SEXP uuidr_uuid_random() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(uuid_random());
    return __result;
END_RCPP
}
// uuid_time
std::string uuid_time();
RcppExport SEXP uuidr_uuid_time() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(uuid_time());
    return __result;
END_RCPP
}
