# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title uuid
#' @name uuid
#' @return uuid string
#' @examples
#' uuid()
uuid <- function() {
    .Call('uuidr_uuid', PACKAGE = 'uuidr')
}

#' @title uuid_random
#' @name uuid_random
#' @return uuid string
#' @examples
#' uuid_random()
uuid_random <- function() {
    .Call('uuidr_uuid_random', PACKAGE = 'uuidr')
}

#' @title uuid_time
#' @name uuid_time
#' @return uuid string
#' @examples
#' uuid_time()
uuid_time <- function() {
    .Call('uuidr_uuid_time', PACKAGE = 'uuidr')
}

