# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

uuid <- function() {
    .Call('uuidr_uuid', PACKAGE = 'uuidr')
}

uuid_random <- function() {
    .Call('uuidr_uuid_random', PACKAGE = 'uuidr')
}

uuid_time <- function() {
    .Call('uuidr_uuid_time', PACKAGE = 'uuidr')
}

